# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 14:52
from __future__ import unicode_literals

import apps.sales.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='День')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Код')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Дни',
                'verbose_name': 'День',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Месяц')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Код')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name_plural': 'Месяцы',
                'verbose_name': 'Месяц',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='Информация')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to=apps.sales.models.upload_location, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активированно')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Созданно')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Дополнительно')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='sales.Day', verbose_name='День')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sales.Month', verbose_name='Месяц')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'verbose_name': 'Акция',
            },
        ),
    ]
