# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='month',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Код'),
        ),
    ]
