# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170610_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
