# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['day__code'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
