# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170628_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysalerel',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_days', to='sales.Day', verbose_name='Дни'),
        ),
        migrations.AlterField(
            model_name='daysalerel',
            name='sales',
            field=models.ManyToManyField(related_name='current_sales', to='sales.Sale', verbose_name='Акции'),
        ),
    ]
