# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170611_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=128, verbose_name='Код'),
        ),
    ]
