# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20170613_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество (250/0.75)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='measure',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ед. измерения (гр./шт./л./мл./на чаше'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
