# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 07:24
from __future__ import unicode_literals

import apps.gallery.models
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170605_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='album',
            name='main_image',
            field=models.ImageField(upload_to=apps.gallery.models.album_upload_location, verbose_name='Обложка'),
        ),
    ]
