# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 08:08
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170712_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
